version: '3.8'

networks:
  roboshop:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongo
    networks:
      - roboshop

  catalogue:
    image: catalogue
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  web:
    image: web
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - mongodb

  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop

  user:
    image: user
    container_name: user
    networks:
      - roboshop
    depends_on:
      - redis
      - mongodb
  
  cart:
    image: cart
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - catalogue
      - redis
