networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image:mongo
    container_name:mongo
    networks:
      -roboshop
  catalogue:
    image:catalogue
    container_name:catalouge
    networks:
      -roboshop
    depands_on:
      -mongodb
  web:
    image:web
    container_name:web
    networks:
      -roboshop
    ports:
    - "80:80"
    depands_on:
      -mongodb